//! Bindings generated by build.rs
#![allow(missing_docs)]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::all)]

/* automatically generated by rust-bindgen 0.72.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RcloneRPCResult {
    pub Output: *mut ::std::os::raw::c_char,
    pub Status: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of RcloneRPCResult"][::std::mem::size_of::<RcloneRPCResult>() - 16usize];
    ["Alignment of RcloneRPCResult"][::std::mem::align_of::<RcloneRPCResult>() - 8usize];
    ["Offset of field: RcloneRPCResult::Output"]
        [::std::mem::offset_of!(RcloneRPCResult, Output) - 0usize];
    ["Offset of field: RcloneRPCResult::Status"]
        [::std::mem::offset_of!(RcloneRPCResult, Status) - 8usize];
};
unsafe extern "C" {
    pub fn RcloneInitialize();
}
unsafe extern "C" {
    pub fn RcloneFinalize();
}
unsafe extern "C" {
    pub fn RcloneRPC(
        method: *mut ::std::os::raw::c_char,
        input: *mut ::std::os::raw::c_char,
    ) -> RcloneRPCResult;
}
unsafe extern "C" {
    pub fn RcloneFreeString(str_: *mut ::std::os::raw::c_char);
}
