//! librclone
//!
//! See the <https://github.com/rclone/rclone/tree/master/librclone> for details.

#[allow(missing_docs)]
#[allow(non_upper_case_globals)]
#[allow(non_camel_case_types)]
#[allow(non_snake_case)]
#[allow(clippy::all)]
pub mod bindings {
    //! Bindings generated by build.rs
    #[cfg(not(docsrs))]
    include!(concat!(env!("OUT_DIR"), "/librclone/bindings.rs"));
}
pub mod rclone;
pub use rclone::Rclone;
